name: Set up Node environment
description: Set up the Node environment to perform various actions in subsequent workflows.

inputs:
  cache_version:
    description: Cache version. Gets appended to the cache key and will therefore invalidate the cache if it changes.
    required: true

runs:
  using: composite

  steps:
    - name: Set up Node
      uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 #v4.0.2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Get npm cache directory
      id: npm-cache
      shell: bash
      run: echo "::set-output name=dir::$(npm config get cache)"

    - name: Cache dependencies
      id: cache-node-dependencies
      uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
      with:
        path: ${{ steps.npm-cache.outputs.dir }}
        key: node-${{ runner.os }}-${{ matrix.node-version }}-${{ hashFiles('package-lock.json') }}-${{ inputs.cache_version }}
