name: Node

on: workflow_call

jobs:
  node:
    name: Node
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 20 ]

    steps:
      - name: Checkout
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4

      - name: Paths filters
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: paths
        with:
          filters: |
            javascript: &javascript
              - '**/*.js'
            eslint:
              - *javascript
              - '.eslintignore'
              - '.eslintrc'
            npm:
              - 'package.json'
              - 'package-lock.json'

      - name: Setup
        if: ${{ toJSON( steps.paths.outputs.changes ) != '"[]"' }}
        uses: ./.github/actions/setup-node
        with:
          cache_version: ${{ secrets.GH_ACTIONS_CACHE_KEY }}

      - name: Install dependencies
        if: ${{ toJSON( steps.paths.outputs.changes ) != '"[]"' && steps.cache-node-dependencies.outputs.cache-hit != 'true' }}
        run: npm ci --progress=false --audit=false --fund=false

      - name: Lint code
        if: ${{ steps.paths.outputs.eslint == 'true' }}
        uses: wearerequired/lint-action@548d8a7c4b04d3553d32ed5b6e91eb171e10e7bb # v2.3.0
        with:
          continue_on_error: false
          eslint: true

      - name: Build application
        if: ${{ steps.paths.outputs.javascript == 'true' || steps.paths.outputs.npm == 'true' }}
        run: npm run build
